"""Initial migration

Revision ID: 4f6f900e46c2
Revises: 
Create Date: 2026-06-01 14:32:08.518214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6f900e46c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('activity_logs', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('jobs', 'updated_on')
    op.drop_column('jobs', 'created_on')
    op.drop_column('candidates', 'updated_on')
    op.drop_column('candidates', 'created_on')
    op.drop_column('activity_logs', 'updated_on')
    op.drop_column('activity_logs', 'created_on')
    # ### end Alembic commands ###
