/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUploadCvRouteImport } from './routes/_app.upload-cv'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPipelineRouteImport } from './routes/_app.pipeline'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppCandidatesRouteImport } from './routes/_app.candidates'
import { Route as AppActivityLogsRouteImport } from './routes/_app.activity-logs'
import { Route as AppJobsJobIdRouteImport } from './routes/_app.jobs.$jobId'
import { Route as AppCandidatesCandidateIdRouteImport } from './routes/_app.candidates.$candidateId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadCvRoute = AppUploadCvRouteImport.update({
  id: '/upload-cv',
  path: '/upload-cv',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogsRoute = AppActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppCandidatesCandidateIdRoute =
  AppCandidatesCandidateIdRouteImport.update({
    id: '/$candidateId',
    path: '/$candidateId',
    getParentRoute: () => AppCandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/candidates': typeof AppCandidatesRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/team': typeof AppTeamRoute
  '/upload-cv': typeof AppUploadCvRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/candidates': typeof AppCandidatesRouteWithChildren
  '/jobs': typeof AppJobsRouteWithChildren
  '/pipeline': typeof AppPipelineRoute
  '/reports': typeof AppReportsRoute
  '/team': typeof AppTeamRoute
  '/upload-cv': typeof AppUploadCvRoute
  '/': typeof AppIndexRoute
  '/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity-logs': typeof AppActivityLogsRoute
  '/_app/candidates': typeof AppCandidatesRouteWithChildren
  '/_app/jobs': typeof AppJobsRouteWithChildren
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/upload-cv': typeof AppUploadCvRoute
  '/_app/': typeof AppIndexRoute
  '/_app/candidates/$candidateId': typeof AppCandidatesCandidateIdRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity-logs'
    | '/candidates'
    | '/jobs'
    | '/pipeline'
    | '/reports'
    | '/team'
    | '/upload-cv'
    | '/candidates/$candidateId'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity-logs'
    | '/candidates'
    | '/jobs'
    | '/pipeline'
    | '/reports'
    | '/team'
    | '/upload-cv'
    | '/'
    | '/candidates/$candidateId'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/activity-logs'
    | '/_app/candidates'
    | '/_app/jobs'
    | '/_app/pipeline'
    | '/_app/reports'
    | '/_app/team'
    | '/_app/upload-cv'
    | '/_app/'
    | '/_app/candidates/$candidateId'
    | '/_app/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload-cv': {
      id: '/_app/upload-cv'
      path: '/upload-cv'
      fullPath: '/upload-cv'
      preLoaderRoute: typeof AppUploadCvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-logs': {
      id: '/_app/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AppActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/_app/candidates/$candidateId': {
      id: '/_app/candidates/$candidateId'
      path: '/$candidateId'
      fullPath: '/candidates/$candidateId'
      preLoaderRoute: typeof AppCandidatesCandidateIdRouteImport
      parentRoute: typeof AppCandidatesRoute
    }
  }
}

interface AppCandidatesRouteChildren {
  AppCandidatesCandidateIdRoute: typeof AppCandidatesCandidateIdRoute
}

const AppCandidatesRouteChildren: AppCandidatesRouteChildren = {
  AppCandidatesCandidateIdRoute: AppCandidatesCandidateIdRoute,
}

const AppCandidatesRouteWithChildren = AppCandidatesRoute._addFileChildren(
  AppCandidatesRouteChildren,
)

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteChildren {
  AppActivityLogsRoute: typeof AppActivityLogsRoute
  AppCandidatesRoute: typeof AppCandidatesRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppPipelineRoute: typeof AppPipelineRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppUploadCvRoute: typeof AppUploadCvRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityLogsRoute: AppActivityLogsRoute,
  AppCandidatesRoute: AppCandidatesRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppPipelineRoute: AppPipelineRoute,
  AppReportsRoute: AppReportsRoute,
  AppTeamRoute: AppTeamRoute,
  AppUploadCvRoute: AppUploadCvRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
